name: First Iteration
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23c0ed'
    - '#222222'
    - '#ffffff'
    - '#1885a4'
    - '#f79520'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
