name: First Iteration
favicon: null
layout_spectrum: 0.1392515681218356
typography_spectrum: 0.4728111275471747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7816610666923225
  lightness: 0.22059058607555926
  saturation: 0.2914608872961253
  rhythmicContrast: 0.05076621100306511
purpose: []
