name: First Iteration
favicon: null
layout_spectrum: 0
typography_spectrum: 0.66165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070709'
    - '#dee7f0'
    - '#a37345'
    - '#8c0001'
    - '#00835c'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
