name: First Iteration
favicon: null
layout_spectrum: 0.1392515681218356
typography_spectrum: 0.4728111275471747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23c0ed'
    - '#222222'
    - '#ffffff'
    - '#1885a4'
    - '#f79520'
  brandStrength: 0.8125
  lightness: 0.22059058607555926
  saturation: 0.2914608872961253
  rhythmicContrast: 0.05076621100306511
purpose: []
